### ISSUE TITLE
How to set the T5 Translator prompt?

### ISSUE THREAD

**Issue by girlsending0** [gonzrubio/EEG-to-Text-Curriculum-Semantic-aware-Contrastive-Learning#10]
Hello, I have a question about setting prompt when using T5-translator.
How to set the prompt ? 
I looked in the code, but couldn't see any T5-related settings.

**Comment by gonzrubio** [comment]
I'm sorry, but T5 is not available in the repo, only BART is. However, it should be straight forward to add it in the model.py file using the transformers library.
